### PR TITLE
fix(ci): make pre-push single-flight runner signal handling portable (Windows SIGHUP crash)

### LINKED ISSUE #9610: fix(ci): make pre-push preflight portable on Windows
## Problem

The repository's linked-worktree pre-push hook cannot run on Windows. A real push from PowerShell reaches `.github/scripts/preflight_runner.py` and crashes before the wrapped checks start:

```text
AttributeError: module 'signal' has no attribute 'SIGHUP'
  at preflight_runner.py:183
```

The signal-forwarding block has two POSIX-only assumptions:

- `signal.SIGHUP` is referenced unconditionally, but Windows Python does not define it.
- `os.killpg` is used for forwarding, but Windows Python does not expose process-group signaling through that API.

This forces Windows contributors to bypass the pre-push hook even when their local checks pass.

## Proposed fix

- Register only signal constants that exist on the current platform.
- Keep `os.killpg` process-group forwarding on POSIX.
- Fall back to `Popen.send_signal()` when `os.killpg` is unavailable.
- Preserve handler restoration and lock cleanup.
- Add platform-simulation unit tests and run the existing single-flight tests on Windows.

## Acceptance criteria

- [ ] `preflight_runner.py -- ...` executes successfully on Windows Python.
- [ ] A normal `git push` can enter and complete the pre-push single-flight checks without `--no-verify`.
- [ ] POSIX process-group forwarding behavior remains unchanged.
- [ ] Tests simulate missing `SIGHUP` and missing `os.killpg`.
- [ ] No dependency changes.

### LINKED ISSUE #9724: Pre-push single-flight runner crashes on Windows without SIGHUP
**Product impact**

- Primary loop layer: Docs-Tooling
- [ ] Involves data loss, failed capture, or broken sync/trust

**Describe the bug**

The installed pre-push hook routes through `.github/scripts/preflight_runner.py`, which assumes POSIX signal APIs are available. On Windows, every `git push` fails before the underlying pre-push checks start.

**To reproduce**

1. On Windows, install/use the repository Git hooks.
2. Push any branch that invokes `scripts/pre-push-singleflight`.
3. Observe `AttributeError: module 'signal' has no attribute 'SIGHUP'` from `run_owned()`.

**Current behavior**

`run_owned()` builds its handler map from `(signal.SIGINT, signal.SIGTERM, signal.SIGHUP)` unconditionally. Windows Python does not expose `SIGHUP`, so the wrapper exits with code 1 and Git rejects the push. The forwarding callback also uses POSIX-only `os.killpg`, which would be another portability hazard if invoked.

**Expected behavior**

The single-flight wrapper should register only signals supported by the host and forward them with a platform-compatible process API, allowing the same pre-push checks to run on Windows.

**Environment**

- Windows 11
- Python 3.11.15
- Git for Windows 2.50+

**Additional context**

Running `scripts/pre-push` directly succeeds; only the single-flight wrapper fails. A regression test should exercise signal selection without requiring a real signal to interrupt the test process.

### PR DESCRIPTION
**Pull request by arhxam**
Fixes #9724.
Fixes #9610.

## Problem

The installed pre-push hook routes through `.github/scripts/preflight_runner.py`. `run_owned()` builds its signal handler map from a hard-coded tuple:

```python
previous_handlers = {
    signum: signal.signal(signum, forward_signal)
    for signum in (signal.SIGINT, signal.SIGTERM, signal.SIGHUP)
}
```

`signal.SIGHUP` is POSIX-only and does not exist on Windows, so merely *constructing that tuple* raises:

```
AttributeError: module 'signal' has no attribute 'SIGHUP'
  at preflight_runner.py:183
```

The wrapper exits 1 and Git rejects the push **before any pre-push check runs**, forcing Windows contributors onto `--no-verify`. `scripts/pre-push` works directly — only the single-flight wrapper fails.

The forwarding callback had the same class of problem: `os.killpg` is POSIX-only, so a signal arriving on Windows would raise `AttributeError` rather than stopping the child.

## Fix

Two module-level seams, so both are testable without sending a real signal to the test process:

- **`forwardable_signals()`** resolves the forward set against the host via `getattr(signal, name, None)`, skipping absent signals instead of exploding. POSIX keeps `SIGINT/SIGTERM/SIGHUP`; Windows gets `SIGINT/SIGTERM`.
- **`signal_child()`** prefers `os.killpg` — the child is started with `start_new_session=True`, so it leads its own process group and the whole tree is reached — and falls back to `child.send_signal()` where process groups are unavailable. It now also swallows `OSError` alongside `ProcessLookupError`, since `killpg` can fail with other OS errors against a dying child.

`run_owned()` becomes:

```python
previous_handlers = {signum: signal.signal(signum, forward_signal) for signum in forwardable_signals()}
```

Handler restoration and lock cleanup in the `finally` block are untouched.

## Acceptance criteria (#9610)

- [x] Register only signal constants that exist on the current platform — `forwardable_signals()`
- [x] Keep `os.killpg` process-group forwarding on POSIX — preferred branch in `signal_child()`
- [x] Fall back to `Popen.send_signal()` when `os.killpg` is unavailable
- [x] Preserve handler restoration and lock cleanup — `finally` block unchanged
- [x] Tests simulate missing `SIGHUP` and missing `os.killpg`
- [x] No dependency changes

The two remaining boxes in #9610 (`preflight_runner.py` executing on Windows Python, and a real `git push` completing there) need a Windows host to sign off — I verified the logic by simulating both missing APIs on POSIX.

## Tests

Added `SignalPortabilityTests` to `.github/scripts/test_pr_preflight.py` (already executed by `repo-checks.yml`), covering:

- signal selection with `SIGHUP` removed — simulating Windows
- `SIGHUP` present on POSIX
- forwarding to the process group when `os.killpg` exists
- `send_signal` fallback when `os.killpg` is absent
- a dead child (`ProcessLookupError`) not raising

## Verification

```
$ python -m unittest test_pr_preflight.SignalPortabilityTests
Ran 5 tests ... OK

# simulating Windows (SIGHUP deleted):
OLD expression      -> AttributeError: module 'signal' has no attribute 'SIGHUP'
forwardable_signals -> ['SIGINT', 'SIGTERM']
```

Full file: 26 tests, with 2 pre-existing failures that are **identical before and after** this change (they require a full clone; my sandbox used a shallow sparse checkout). `black --check --line-length 120` → clean, matching the pinned CI formatter.

---
🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Failure class

Failure-Class: none

Windows-only signal API portability in a repo tooling script; no registered class covers host-API availability in the pre-push runner.

### CODE REVIEW

**Review by Git-on-my-level — COMMENTED** [review]
Thanks for the focused fix — this looks like the right shape for the Windows `SIGHUP` crash in the pre-push single-flight runner.

What I checked:
- `forwardable_signals()` avoids importing/registering signal constants that the host Python does not define, so Windows should no longer fail before the pre-push checks start.
- `signal_child()` keeps POSIX process-group forwarding via `os.killpg` and falls back to `Popen.send_signal()` when process groups are unavailable.
- The new unit coverage exercises missing `SIGHUP`, missing `os.killpg`, POSIX process-group forwarding, and dead-child handling without sending real signals to the test process.
- I ran `python -m unittest test_pr_preflight.py` from `.github/scripts` in a clean environment on this head; all 26 tests passed. The focused `SignalPortabilityTests` also passed separately.

I’m leaving this as a positive maintainer signal rather than a formal approval because it changes repo hook/CI tooling under `.github/scripts`, so a human maintainer should make the final call before merge. I did not find a blocker in the code itself.

---
*by AI on behalf of David — if you need David’s attention urgently, please @Git-on-my-level and escalate with `need human response`.*

**Comment by tianmind-studio** [comment]
Native Windows follow-up: the signal-selection helper in this PR fixes the first `SIGHUP` exception, but a real hook-driven push still cannot complete on current Windows. After applying this layer I reproduced three subsequent host boundaries:

- `process_exists()` uses `os.kill(pid, 0)`; signal 0 is `CTRL_C_EVENT` on Windows and interrupted the shared console.
- The extensionless `scripts/pre-push` cannot be passed directly to native `CreateProcess`.
- A bare `bash` launched from native Python can resolve to `C:\Windows\System32\bash.exe` instead of the Git Bash already running the hook.

The direct-child `send_signal()` fallback also cannot contain descendants.

The signal seam itself is useful, but the current `Fixes #9610/#9724` scope overstates end-to-end Windows readiness. #10574 carries the host-tested full chain (supported signals, non-destructive PID identity, Git Bash/Python binding, Job Object descendant cleanup, UTF-8 paths, and a native Windows workflow), with all CI green and a positive collaborator review.

I recommend either narrowing this PR to the helper-only layer or coordinating it with that complete integration so maintainers do not merge two conflicting partial implementations.

File: .github/scripts/preflight_runner.py [hunk 1]
```diff
@@ -17,6 +17,35 @@
...
+    The child is started with ``start_new_session=True``, so on POSIX it leads its
+    own process group and ``os.killpg`` reaches the whole tree. Windows has no
+    ``os.killpg``; fall back to signalling the process directly.
+    """
+    killpg = getattr(os, "killpg", None)
+    try:
+        if killpg is not None:
+            killpg(child.pid, signum)
+        else:
+            child.send_signal(signum)
```
Comment (tianmind-studio) [inline .github/scripts/preflight_runner.py:45]: `forwardable_signals()` registers `SIGINT` on Windows, but Windows `Popen.send_signal()` does not accept `signal.SIGINT` (`2`); it accepts `SIGTERM` or the Windows console-control events. On a native Windows Python 3.12 checkout I reproduced this with a real `start_new_session=True` child: `signal_child(child, signal.SIGINT)` raises `ValueError: Unsupported signal: 2`. `ValueError` escapes this handler, and `run_owned()`'s `finally` does not stop the still-running child. Please map interruption to a supported Windows mechanism (and create the needed process group if using a console-control event), or use a deliberate termination fallback, then cover the real Windows signal value rather than only mocked `SIGTERM`.

File: .github/scripts/test_pr_preflight.py [hunk 2]
```diff
@@ -494,5 +496,59 @@ def test_different_input_is_rejected_while_active(self) -> None:
...
+                delattr(os, "killpg")  # simulate Windows
+            preflight_runner.signal_child(child, signal.SIGTERM)
+        finally:
+            if had_killpg:
+                os.killpg = original
+        child.send_signal.assert_called_once_with(signal.SIGTERM)
+
+    def test_forwarding_swallows_dead_child(self) -> None:
+        child = Mock(pid=4321)
+        with patch.object(os, "killpg", side_effect=ProcessLookupError):
```
Comment (tianmind-studio) [inline .github/scripts/test_pr_preflight.py:549]: This new portability suite does not pass on the platform it targets. Native Windows has no `os.killpg`, so `patch.object(os, "killpg", ...)` raises `AttributeError` before `signal_child()` runs. Repro from `.github/scripts`: `py -3 -m unittest test_pr_preflight.SignalPortabilityTests` -> 5 tests, 1 error, 2 skipped. Please create/inject the missing callable explicitly (for example `create=True`) or exercise the platform-neutral seam without assuming the POSIX attribute exists.

**Review by tianmind-studio — CHANGES_REQUESTED** [review]
Native Windows review on CPython 3.12 found two reproducible blockers in the portability path. A real child passed through `signal_child(..., signal.SIGINT)` raises `ValueError: Unsupported signal: 2`, and the focused test class currently reports `FAILED (errors=1, skipped=2)` on Windows. I included the exact failure sites and focused fixes inline. The `SIGHUP` selection change itself is sound.

**Review by Git-on-my-level — CHANGES_REQUESTED** [review]
Thanks for continuing to narrow this. The `SIGHUP` registration seam is useful, but I think the current head still needs changes before this can be treated as a Windows pre-push fix.

Blocking points I see:

- In the Windows fallback path, `signal_child(child, signal.SIGINT)` reaches `child.send_signal(signal.SIGINT)` when `os.killpg` is unavailable. Native Windows `Popen.send_signal()` does not provide POSIX `SIGINT` semantics for a child process the way the test mock assumes, so an interrupted hook can still fail instead of cleanly stopping/forwarding. The current test only checks a mocked `send_signal(signal.SIGTERM)` call, so it does not cover the failing `SIGINT` path or real Windows `Popen` behavior. Please either avoid forwarding unsupported signals in the direct-child fallback, map to a Windows-supported console-control/termination behavior with the right process creation constraints, or otherwise make interruption safe on Windows, with coverage that exercises that path.
- The PR still presents this as fixing the end-to-end Windows pre-push hook, but the runner has other native-Windows boundaries that this patch does not address. For example, `process_exists()` still uses `os.kill(pid, 0)`, and the actual hook command path still needs to be valid when launched by native Windows Python. If this PR is intended to be a small first layer, please narrow the claims/acceptance wording so maintainers do not merge it as the complete `#9610`/`#9724` fix.

I ran the focused `SignalPortabilityTests` and the full `.github/scripts/test_pr_preflight.py` suite on Linux at `de1eda489f882b2b2a1bce0c912e5db437b32888`; both pass locally (`5` focused tests, `26` full tests). So the POSIX side looks okay, but the Windows-specific behavior the PR is meant to fix is still under-covered and appears incomplete.

---
*by AI on behalf of David — if you need David’s attention urgently, please @Git-on-my-level and escalate with `need human response`.*

**Review by kodjima33 — APPROVED** [review]
Verified against #9724/#9610: preflight_runner.py still hard-codes signal.SIGHUP on main, which does not exist on Windows and crashes the pre-push hook; the fix filters to the signals the platform actually has.
