### PR TITLE
feat(mcp): add scoped People rename and cleanup tools

### LINKED ISSUE #8369: Follow up after canonical memory rollout: safe MCP People/entity cleanup tools
## Context

This is the replacement/follow-up issue for:

- Original request: #8204
- Draft implementation PR: #8346
- Canonical memory rollout integration branch on the fork: https://github.com/Git-on-my-level/omi/pull/33

The old request is still valid: MCP clients can read People/contact records via `get_people`, but they cannot clean up false positives, duplicates, or incorrect display names through MCP-only workflows.

However, the draft PR grew into a broader mix of People cleanup tools, MCP API-key scope semantics, REST/SSE scope enforcement, and compatibility handling. That makes it the wrong PR shape to merge before the canonical memory domain rollout lands upstream.

## Follow-up timing

Do this **after** the canonical memory rollout from fork PR https://github.com/Git-on-my-level/omi/pull/33 has been decomposed/merged upstream, or after the relevant MCP memory/auth foundation from that branch is available on upstream `main`.

The follow-up should be based on upstream `main` after that landing, not on the older #8346 branch.

## Goal

Expose a safe, scoped MCP surface for People/entity cleanup so trusted clients can:

1. List People/contact/entity records.
2. Correct display names.
3. Dismiss/archive false-positive records.
4. Eventually merge duplicates or perform hard deletion only when the backend/product semantics support it safely.

### 1. Keep the PR narrow

Do not combine all of these in one upstream PR:

- new People mutation tools
- API-key scope schema changes
- REST route scope enforcement
- SSE tool scope enforcement
- legacy key compatibility migration
- hard-delete data cleanup semantics

That made #8346 hard to review and generated many rounds of legitimate feedback. The next PR should assume the canonical/auth foundation already exists, or split foundation changes first.

### 2. Do not duplicate MCP scope/auth infrastructure from the canonical rollout

Fork PR #33 already introduces MCP API-key `app_id` / `scopes` auth context and converges MCP memory writes onto `MemoryService` for canonical users.

After that lands, the People cleanup follow-up should reuse the landed auth context and route/tool enforcement patterns instead of reintroducing a separate scope model.

### 3. Prefer soft cleanup before hard delete

`delete_person` is too sharp as the first MCP People write primitive. MCP tools are model-controlled, and clients may vary in how well they present human confirmation for destructive calls.

Prefer a safer progression:

1. `rename_person(person_id, name)` — non-destructive correction.
2. `dismiss_person(person_id)` / `archive_person(person_id)` / `mark_person_false_positive(person_id)` — soft cleanup, excluded from default People reads.
3. `merge_people(source_person_id, target_person_id)` — later, once product semantics are clear.
4. `delete_person(person_id)` — only if hard-delete semantics, cleanup/retry, and authorization are explicitly defined.

### 4. Treat destructive capability as opt-in

Do not silently grant destructive People write access to every newly-created MCP key just because it defaults to all scopes.

Recommended policy:

- legacy keys keep their pre-existing behavior;
- new default keys should not automatically gain destructive People cleanup;
- `people.write` or a narrower `people.cleanup` / `people.delete` scope should be explicitly requested/granted;
- if separate scopes are available, use `people.rename` and `people.cleanup` / `people.delete` rather than one broad write scope.

### 5. Scope enforcement must be consistent across transports

If a People cleanup capability is exposed in both MCP SSE/Streamable HTTP tools and REST `/v1/mcp/*` endpoints, enforce the same scope semantics on both. Avoid drift between advertised `securitySchemes` and actual runtime checks.

### 6. `tools/list` should not encourage unusable destructive calls

For keys that lack the write/cleanup scope, consider filtering unavailable write tools from `tools/list` or marking them clearly as unavailable. Returning all tools and failing with an insufficient-scope error at call time is compatible, but worse for agent ergonomics.

### 7. Hard-delete cleanup must be durable if/when implemented

If hard delete remains necessary, avoid fire-and-forget storage cleanup that returns success even if blob cleanup later fails. Prefer one of:

- transactional/awaited cleanup when feasible;
- a durable cleanup job with retry and observable status;
- soft-delete first, then asynchronous hard cleanup with retry/audit.

## Proposed follow-up scope after fork PR #33 lands

Start with the smallest safe upstream PR:

- Reuse landed canonical MCP auth context / scope infrastructure.
- Add a scoped non-destructive `rename_person` tool.
- Add a soft cleanup tool if the backend has or can cheaply add a soft state (`dismiss_person`, `archive_person`, or equivalent).
- Do **not** add hard delete unless product/backend deletion semantics and durable cleanup are in place.
- Add regression tests for:
  - descriptor metadata and annotations;
  - scope enforcement for allowed and disallowed keys;
  - legacy key behavior;
  - REST/SSE parity if both surfaces expose the feature;
  - no transcript/sample leakage from write-only responses;
  - soft-dismiss exclusion from default `get_people` reads.

## Acceptance criteria

- [ ] Implementation is based on upstream `main` after the canonical memory/auth foundation lands.
- [ ] People cleanup tools reuse the landed MCP auth/scope context instead of creating parallel scope infrastructure.
- [ ] Non-destructive rename is supported via MCP.
- [ ] False-positive cleanup is soft by default, or hard delete is explicitly justified with durable cleanup semantics.
- [ ] Destructive cleanup is not granted to legacy keys or default new keys without explicit opt-in.
- [ ] Scope enforcement is consistent across MCP transports/routes.
- [ ] `tools/list` behavior is deliberate for keys without cleanup scope.
- [ ] Tests cover compatibility and security cases from #8346 review feedback.

## References

- #8204 — original feature request for hosted MCP People/contact cleanup tools.
- #8346 — draft PR that explored implementation and surfaced scope/deletion compatibility lessons.
- https://github.com/Git-on-my-level/omi/pull/33 — canonical memory rollout branch; follow up only after the relevant foundation lands upstream.

### PR DESCRIPTION
**Pull request by aryanorastar**
## Summary

- add hosted MCP and REST operations to rename a recognized person and dismiss a false-positive person
- require `people.rename` for corrections and an explicit opt-in `people.cleanup` scope for dismissal
- keep existing and default API keys backward-compatible without silently granting cleanup access
- preserve dismissed records, aliases, history, and speech data while excluding them from normal People reads
- publish the new routes in the OpenAPI contract, generated desktop/web clients, and MCP documentation

### Rename

`rename_person` updates the display name while retaining the prior name in a bounded alias list. It is owner-scoped and returns only the person ID and corrected name; it does not return transcript samples.

### Dismiss

`dismiss_person` is deliberately a soft cleanup operation. It records `is_dismissed`, `dismissed_at`, and `updated_at`, and normal People reads skip the record. The operation is idempotent, preserves the original dismissal timestamp, and maps missing or concurrently deleted records to a not-found response.

This PR does **not** hard-delete a person, speech samples, audio, or historical data. Portability exports explicitly include dismissed people so cleanup does not remove user data from export.

### Authorization

- `people.read` remains the read scope.
- `people.rename` is included in the compatibility/default scope set so existing clients retain safe correction behavior.
- `people.cleanup` is supported by OAuth and API keys but is never added implicitly to legacy, default, or newly created keys.
- API-key creation accepts recognized explicit scopes and rejects unknown scopes.
- `tools/list` hides `dismiss_person` unless the caller has `people.cleanup`.
- runtime tool dispatch and REST routes independently enforce the required scope.
- REST calls retain the existing fail-closed per-app/per-key MCP rate limit.

## API surface

- hosted MCP tools: `rename_person`, `dismiss_person`
- `PATCH /v1/mcp/people/{person_id}/name`
- `POST /v1/mcp/people/{person_id}/dismiss`
- reviewed route-policy entries for both REST operations
- regenerated app-client OpenAPI, macOS Swift, Windows TypeScript, and web TypeScript bindings

## Test evidence

- 216 focused backend tests across People storage, MCP tools/REST, OAuth/API-key scopes, key creation, and dependency boundaries
- targeted GDPR/data-export coverage confirms dismissed and locked user data remains exportable
- tool descriptor, `tools/list`, allowed/denied scope, validation, not-found, idempotency, concurrent deletion, transcript-leak, and legacy/default-key regression coverage
- public, app-client, and integration OpenAPI freshness checks
- TypeScript, Swift, and Dart generated-client freshness checks
- Python compile/format and diff hygiene checks
- full local repository preflight (46 selected checks)

The local Node 26 run uses `NODE_OPTIONS=--no-experimental-webstorage` so Vitest/jsdom owns `localStorage`; this only avoids a Node runtime collision and does not alter product behavior.

## Product invariants affected

- INV-MEM-3 — the export path continues to use the universal memory authority; this change only makes People export include soft-dismissed records and does not add a legacy memory read path.

## Failure class

None. This is a new, scoped cleanup capability rather than a change to an existing runtime failure class.

Closes #8369

<a href="https://cubic.dev/pr/BasedHardware/omi/pull/15669?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Comment by Git-on-my-level** [comment]
Thanks @aryanorastar — this is one of the more carefully scoped permission changes I've reviewed on this repo. The opt-in design for `people.cleanup` holds up end to end, and I want to walk through why before raising three product questions that need a maintainer call.

**What I verified**

- `backend/utils/mcp_scopes.py` — `normalize_mcp_scopes` now returns default ∪ (requested ∩ `MCP_OPT_IN_SCOPES`). This is the crucial line: lazy repair of legacy keys flows through it, so existing keys can never silently acquire `people.cleanup`. Renaming `MCP_FULL_ACCESS_SCOPES` → `MCP_DEFAULT_API_KEY_SCOPES` with a compat re-export is a good move.
- `backend/routers/api_key_management.py` — unknown scopes rejected with 400 before persistence; explicit `scopes=["people.cleanup"]` at creation is the only path to a cleanup key.
- `backend/routers/mcp_sse.py` — `dismiss_person` is hidden from `tools/list` without the scope (`_tools_for_scopes`) *and* re-checked at `tools/call` (`_require_tool_scope`), so neither endpoint trusts the other. The scope-permission strings ("Dismiss false-positive people…") are honest about impact.
- `backend/dependencies.py` / `backend/routers/mcp.py` — `require_mcp_api_key_scope` returns only the owner UID, and each REST route pins a distinct scope dependency; `test_rest_people_routes_use_matching_scope_dependencies` locks that wiring in.
- `backend/database/person_aliases.py` — dismissal transaction is soft (`is_dismissed`/`dismissed_at` only), idempotent (early-return preserves the first timestamp), and maps concurrent deletion to 404 rather than 500. `find_person_by_name` dropping `.limit(1)` is fine since it now iterates to the first *non-dismissed* match.
- `backend/services/users/data_export.py` — exports pass `include_dismissed=True`, so cleanup never removes data from the user's portable archive. Good privacy-preserving default pairing.
- `backend/route_policy_manifest.yaml`, `backend/utils/mcp_people.py`, `backend/utils/mcp_analytics.py` — manifest entries match the implemented auth/rate-limit placement; `mcp_people.py` keeps descriptors and execution co-located with `DESTRUCTIVE_WRITE_ANNOTATIONS` on dismiss; analytics events wired for the new tools.
- Generated clients (`OmiApi.generated.swift`, the four `omiApi.generated.ts`) and `app-client-openapi.json` are consistent regenerations.

**Product questions for a maintainer (not blockers from me, but they decide the shape of the feature):**

1. **`people.rename` joins the default grant** (`MCP_DEFAULT_API_KEY_SCOPES`). Every existing key gains rename on its next auth via lazy repair, silently. "Corrections are safe" is defensible, but it's a write capability arriving on legacy keys without any user action — and it invites the symmetric question: if rename is default-safe, why isn't cleanup? Worth an explicit product decision rather than an implicit one.
2. **One-way dismissal.** The record survives in storage and export, but there's no un-dismiss path in the app, REST, or MCP — a wrong dismissal means support intervention. Is that acceptable for v1?
3. **`get_people` semantics reach beyond MCP.** `backend/database/users.py` now filters dismissed people by default, and callers include the core app people list (`routers/users.py`), speaker matching (`routers/listen/speakers.py`), and person-creation dedupe (`get_person_by_name`). The last one is the sharpest edge: re-creating the same name now produces a duplicate person instead of resurrecting the dismissed one. Reasonable default, but the blast radius is the app, not just MCP — worth confirming that's the intended product behavior.

One small non-blocking note: `require_mcp_api_key_scope` hardcodes `policy_name="mcp:read"` for the rename/dismiss dependencies. The manifest matches, so it's consistent today — just flagging that writes ride a read-named policy.

**Docs note:** the MCP docs (`introduction.mdx`, `tools.mdx`, `setup.mdx`) now advertise rename/dismiss to AI agents. I checked each claim against the enforcement code above and they're accurate, including that `people.cleanup` is never granted by default — good, since these docs directly steer agent tool selection. The destructive-write annotation on dismiss is the right conservative signal.

Backend checks are green (one desktop contract check still queued at review time). Leaving the three questions above for maintainer product decisions before merge.

🤖 Automated review on behalf of the maintainers.

---
*by AI on behalf of David — if you need David’s attention urgently, please @Git-on-my-level and escalate with `need human response`.*

**Comment by aryanorastar** [comment]
Conflict resolved on `ad9ca18094` — merge of current main, no change to this diff.

**Six files conflicted, and only one needed a decision.** `route_policy_manifest.yaml` was the familiar list-head collision: main added `POST /v1/mobile/feedback` at the same position this branch adds the two MCP People routes, and git spliced the three entries into each other rather than picking one. Resolved as the union, with each entry rebuilt whole rather than stitched — a half-merged policy entry would claim the wrong auth mechanism for a route, which is the one failure this file cannot afford.

Verified by parsing rather than by eye: 157 entries against main's 155, the two added are this PR's (`PATCH /v1/mcp/people/{person_id}/name`, `POST /v1/mcp/people/{person_id}/dismiss`), none dropped, no duplicate paths.

**The other five are generated clients, so they were regenerated, not merged.** `OmiApi.generated.swift` and the four `omiApi.generated.ts` files were rewritten from the committed contract via `generate_swift_openapi_types.py` and `generate_ts_openapi_types.py`. Hand-resolving generated output produces a file that matches neither side and drifts from its source the moment anyone re-runs the generator.

**Verification on the merged head:**

- `generate_ts_openapi_types.py --check`, `generate_swift_openapi_types.py --check`, `generate_dart_models.py --all --check` — all up to date, exit 0
- `export_openapi.py --surface app-client --check` — `app-client-openapi.json` is up to date
- `route_policy_inventory.py --check` clean; `check_route_policy_baseline.py --base-ref origin/main` — baseline current, 0 stale entries
- the eight test files this PR touches, each in isolation: 404 passed (`test_mcp_data_endpoints` 89, `test_mcp_oauth` 62, `test_daily_memory_sweep` 195, plus the API-key, auth-context, people-500s, update-person and dependency-boundary suites)
- `git diff origin/main...HEAD` unchanged in shape at 31 files, backend, docs and generated clients only

One note on that test evidence, since the number moved while I was checking: running all eight files in a single pytest process produces 47 failures, and the same kind of cross-file interference reproduces on main with its own file set. Every file passes alone, which is the standard the sharded backend lanes hold them to. I am reporting that rather than only the green number.

**Nothing here touches the three product questions from the review** — whether `people.rename` belongs in the default grant, whether one-way dismissal is acceptable for v1, and whether `get_people` filtering dismissed records app-wide (notably the create-person dedupe path) is the intended blast radius. Those are still maintainer calls, and the merge does not change any of them.

**Comment by Git-on-my-level** [comment]
Follow-up verification after the merge of current main at ad9ca18 (the earlier automated review was pre-merge).

Independently re-checked the rebase rather than taking it on trust:

- `backend/route_policy_manifest.yaml` parses clean: 157 entries, no duplicate (method, path) pairs, and the two added entries (`PATCH /v1/mcp/people/{person_id}/name` -> `people.rename`, `POST /v1/mcp/people/{person_id}/dismiss` -> `people.cleanup`) carry the dependency-placed auth and fail-closed `mcp:read` rate limit the code actually implements - no half-spliced policy entries survived the conflict resolution.
- The four regenerated `omiApi.generated.ts` clients are byte-identical to each other and consistent with the `app-client-openapi.json` additions (`McpPersonMutationResponse`, `McpPersonRenameRequest`, optional `scopes` on `McpApiKeyCreate`); `OmiApi.generated.swift` matches the same contract.
- Diff shape vs base is unchanged: 31 files, backend + docs + generated clients only.
- Security envelope re-verified at this head and unchanged from the earlier review: `normalize_mcp_scopes` still returns default + explicitly requested opt-in, so legacy-key lazy repair cannot mint `people.cleanup`; `tools/list` filtering and the `tools/call` re-check in `backend/routers/mcp_sse.py` remain independent; the REST dependencies in `backend/routers/mcp.py` pin one scope per route and return only the owner UID. All checks are green on this head, including the desktop contract lane that was still queued last time.

The three product questions from the earlier review are the remaining merge gate, and the merge changed none of them: (1) whether `people.rename` should join the default grant that legacy keys acquire silently on next auth, (2) whether one-way dismissal with no un-dismiss path is acceptable for v1, and (3) whether filtering dismissed records in `get_people` app-wide - including the create-person dedupe path in `get_person_by_name` - is the intended blast radius beyond MCP. Those are direction calls, not code defects; the implementation of what this PR claims to do checks out.

Docs: `introduction.mdx`/`tools.mdx`/`setup.mdx` now advertise `rename_person` and `dismiss_person` to connecting AI agents. Each claim still matches the enforcement code, and the `dismiss_person` descriptor carries the destructive-write annotation in the tool listing itself - accurate agent-facing guidance.

🤖 Automated review on behalf of the maintainers.

---
*by AI on behalf of David — if you need David’s attention urgently, please @Git-on-my-level and escalate with `need human response`.*

**Comment by aryanorastar** [comment]
Conflicts resolved on `e65ae17040` — merge of current `main`, no change to this diff. Back to **MERGEABLE** at 31 files, +1205/−69, the same shape as before the merge.

All five conflicts were generated clients, so they were **regenerated, not merged**: `OmiApi.generated.swift` and the four `omiApi.generated.ts`. Hand-resolving generated output produces a file that matches neither side and drifts from its source the moment anyone re-runs the generator. Each conflicted file was reset to `main`'s copy first, then rebuilt from the committed contract via `generate_ts_openapi_types.py` and `generate_swift_openapi_types.py`.

`docs/api-reference/app-client-openapi.json` auto-merged cleanly and kept both routes and both schemas (`/v1/mcp/people/{person_id}/name`, `/v1/mcp/people/{person_id}/dismiss`, `McpPersonMutationResponse`, `McpPersonRenameRequest`), so the regeneration had the right source.

One thing worth stating plainly, since it looks like a regression at a glance: `OmiApi.generated.swift` contains no `McpPerson*` type names. That is correct — the Swift generator types request and response bodies as `OmiAnyCodable` rather than emitting named structs. Both routes are there as `renamePersonV1McpPeoplePersonIdNamePatch` and `dismissPersonV1McpPeoplePersonIdDismissPost`, and the file's own footer moved from `Total: 444` to `Total: 446 Swift client methods generated`.

`main` advanced by two commits partway through verification, so those were merged as well; the branch is at 0 behind `main`.

### Verification on the merged head

| check | result |
|---|---|
| `generate_ts_openapi_types.py --check` | rc=0 |
| `generate_swift_openapi_types.py --check` | rc=0 |
| `generate_dart_models.py --all --check` | rc=0 |
| `export_openapi.py --surface app-client --check` | `app-client-openapi.json is up to date` |
| `check_route_policy_baseline.py --base-ref origin/main` | `route policy missing-route baseline is current` |

`route_policy_manifest.yaml` verified by parsing rather than by eye: **158 entries against main's 156**, no duplicate `(method, path)` pairs, exactly two added (`PATCH …/name`, `POST …/dismiss`), none dropped.

The eight test files this PR touches, each run in isolation — **404 passed**: `test_mcp_data_endpoints` 89, `test_mcp_oauth` 62, `test_daily_memory_sweep` 195, `test_api_key_route_contract` 11, `test_dependency_async_boundaries` 12, `test_mcp_api_key_auth_context` 8, `test_people_conversations_500s` 16, `test_update_person_missing` 11.

### Two things I did *not* carry into this PR

`backend/routers/apps.py` and `backend/tests/unit/test_apps_exception_hardening.py` are not clean under this repo's own pinned Python formatter — running it on `main`'s committed bytes reformats both. The pre-commit hook therefore rewrites them whenever a merge stages them. This branch does not touch either file, so both were reverted to `main`'s exact bytes rather than letting unrelated reformatting ride along in the diff. Flagging it because it will keep happening to every merge that touches them.

`route_policy_inventory.py --check` fails locally here, but it fails identically in a separate checkout on an unrelated branch, so it is an environment condition rather than anything this PR introduced. The delta check that is scoped to this change — `check_route_policy_baseline --base-ref origin/main` — passes.

Nothing in this merge touches the three product questions from the review: whether `people.rename` belongs in the default grant, whether one-way dismissal is acceptable for v1, and whether `get_people` filtering dismissed records app-wide (notably the create-person dedupe path) is the intended blast radius. Those remain maintainer calls.

**Comment by aryanorastar** [comment]
Hygiene is green-able again on `32c37c8a89`. The failing check was `mcp-category-filter-tests`, and the cause is a latent bug in that test's own harness rather than anything in this diff — but it is worth spelling out, because the reason it reached CI at all is a Python version difference that will bite the next person the same way.

### What failed

```
AttributeError: module 'requests' has no attribute 'Response'
  mcp/src/mcp_server_omi/server.py:136, in _response_json
```

The Hygiene job installs only `pyyaml`, so the real `requests` is absent and `_ensure_third_party_imports()` falls back to `_fake_requests_module()`. That stub carries `HTTPError`, `get`, `post`, `delete` and `patch` — every attribute the tests *call* — but not `Response`, which `server.py` names in a signature:

```python
def _response_json(response: requests.Response):
```

Before 3.14's deferred annotation evaluation (PEP 649), Python evaluates that annotation at import time, so importing the module under the stub raises before a single test runs.

### Why it passed locally and failed in CI

My `python3` is 3.14.6, where the annotation is never evaluated, so the check passed here. CI pins 3.11.15 via `backend/.python-version`, where it is evaluated eagerly. I reproduced the exact CI `AttributeError` on 3.11.15 by hiding `requests` to force the stub path, then verified the fix on all three combinations:

| interpreter | `requests` | result |
|---|---|---|
| 3.11.15 | stub (the CI path) | 8 tests OK |
| 3.11.15 | real | 8 tests OK |
| 3.14.6 | real | 8 tests OK |

### The fix

One attribute on the stub, in its own commit (`18ec74f58b`) separate from the merge, per the root `AGENTS.md`:

```python
class Response:
    """Annotation target for server.py's _response_json signature."""

module.Response = Response
```

### Why this PR is the one carrying it

This PR touches neither of that check's triggers (`mcp/**`, `.github/checks-manifest.yaml`). It got selected because merging current `main` brought in `8e8f3f80bb`, which edits `.github/checks-manifest.yaml` — so the merge put a trigger path into the changed-file set CI computes. Any PR that merges `main` past that commit will select this check and hit the same import error, which is why I fixed it here rather than just re-running. A plain re-run of the job failed identically, as expected.

Diff is now **32 files** — the PR's 31, unchanged, plus `mcp/tests/test_category_filters.py`. Current `main` merged again (it moved five commits mid-verification); branch is at 0 behind. Generated-client freshness re-checked after that merge: `generate_ts_openapi_types --check`, `generate_swift_openapi_types --check` and `export_openapi --surface app-client --check` all rc=0.

The three product questions from the review are still untouched and still maintainer calls.

**Comment by aryanorastar** [comment]
`Backend unit shard 3/4` is red here, but the break is on `main`, not in this PR. Evidence rather than assertion:

```
FAILED tests/unit/test_app_client_schema_inventory.py::test_inventory_openapi_route_response_decode_migration_complete
AssertionError: assert not response_violations
```

The single violation is `app/lib/backend/http/api/conversations.dart:549`, route `/v1/conversations/{param}/capture-group/separate` — a raw response decode with no generated-model backing. This PR touches neither that file nor that route; `git diff origin/main HEAD -- docs/api-reference/app-client-openapi.json` has zero `capture-group` hits, and the diff contains no `app/` files at all.

### Bisected to the commit

I checked out pristine trees and ran the same test:

| tree | result |
|---|---|
| `origin/main` @ `29b3c32299` | **1 failed**, 11 passed |
| `373126c05e` — *feat(app): one row per recorded event and a compact conversation page on mobile (#17297)* | **1 failed**, 11 passed |
| `373126c05e^` | **12 passed** |

So `373126c05e` introduced it, and current `main` still carries it. Any PR that merges `main` past that commit inherits this red, which is why it appeared here one merge after it appeared everywhere else.

I have not touched it. The fix belongs in the Flutter client — either routing that decode through a generated model or recording it the way the inventory expects — which is outside this PR's scope and outside what I work on. Flagging it so it gets an owner rather than being mistaken for fallout from this change.

The `Backend unit suite` failure is the same shard rolled up; there is no second cause.

For the record, everything this PR *is* responsible for still passes on the current head `32c37c8a89`: the eight touched test files at 404 passed in isolation, `mcp-category-filter-tests` OK after the stub fix, and `generate_ts_openapi_types --check`, `generate_swift_openapi_types --check` and `export_openapi --surface app-client --check` all rc=0.

**Comment by aryanorastar** [comment]
The `Backend unit shard 3/4` red here is fixed by BasedHardware/omi#18491, opened against `main`.

That PR migrates `separateConversationFromCaptureGroup` to decode through a generated `GeneratedStatusResponse` instead of a raw `jsonDecode` + `body['status']`, which is what `test_inventory_openapi_route_response_decode_migration_complete` has been failing on since `373126c05e`. Since the break is on `main`, it unblocks every PR that merges past that commit, not just this one — which is why it is a separate PR rather than a commit bundled in here. This PR's diff stays at the 32 files described above.

Nothing on this branch changes as a result.

**Review by kodjima33 — APPROVED** [review]
feat(mcp): new People rename/dismiss capability with scoped auth -- feature, approve-only per policy regardless of score. Backend unit shard 3/4 and Backend unit suite are currently failing.

**Comment by aryanorastar** [comment]
Conflicts resolved on `006c64bb42` — merge of current `main` (19 commits), no change to this diff. Back to **MERGEABLE** at 32 files, +1214/−69.

Same five generated clients conflicted as last time, handled the same way: reset each to `main`'s copy and rebuilt from the committed contract rather than hand-merging. `docs/api-reference/app-client-openapi.json` auto-merged cleanly and kept both routes and both schemas, so the regeneration had the right source.

### Verification on the merged head

| check | result |
|---|---|
| `generate_ts_openapi_types.py --check` | rc=0 |
| `generate_swift_openapi_types.py --check` | rc=0 |
| `generate_dart_models.py --all --check` | rc=0 |
| `export_openapi.py --surface app-client --check` | rc=0 |

`route_policy_manifest.yaml` parsed rather than eyeballed: **165 entries against main's 163**, no duplicate `(method, path)` pairs, exactly two added (`PATCH …/name`, `POST …/dismiss`), none dropped.

The eight test files this PR touches, each in isolation: **404 passed**, unchanged. `mcp-category-filter-tests` OK.

### One thing kept out of the diff

The pre-commit hook reformatted `backend/tests/unit/test_shared_action_items.py` — a file this branch does not touch. `main`'s committed bytes for it are not clean under the repo's own pinned Python formatter, so any merge that stages it picks up the reformat. Reverted to `main`'s exact bytes, same as `backend/routers/apps.py` in the previous merge. Worth a look at why those files and the pinned formatter disagree, since it will keep happening.

The remaining red (`Backend unit suite`, `Backend unit shard 3/4`) is still `main`'s schema-inventory break from `373126c05e`, fixed by #18491 and not by anything on this branch. It will clear here once that lands and `main` is merged again.

The three product questions from the review are untouched and still maintainer calls.

**Comment by aryanorastar** [comment]
The `Backend unit shard 4/4` red here is another `main`-side break, not this PR's, and it is fixed by BasedHardware/omi#18719.

`tests/unit/test_shared_action_items.py` fails with `TypeError: accept_shared_action_items() got an unexpected keyword argument 'payload'`. Reproduced on a pristine `origin/main` checkout: 6 failed. Bisected to `b2c9cfb199` (#17830), the commit that added the file — the tests were written against an API that does not exist (`payload=` vs the handler's `request`, `verify_task_share_token` vs `get_task_share`, `get_action_items_by_ids` vs `get_action_item`), so they have never passed since they landed.

This branch does not touch that file — its bytes here are identical to `main`'s. #18719 rewrites the tests against the handler they actually test; no production behavior changes.

Nothing on this branch changes as a result.
