### ISSUE TITLE
Desktop release-mode test build broken on main since #13235: RealtimeTurnEvidenceTests uses a #if DEBUG seam unguarded

### ISSUE THREAD

**Issue by Git-on-my-level** [BasedHardware/omi#13458]
## Symptom

`desktop/macos/scripts/run-swift-ci.sh --release-notification-regression` (step **Test UserNotifications callback regression in release mode** of the Desktop Swift Release Compile job) fails on any PR that touches `desktop/macos/Desktop/Tests/*.swift`:

```
desktop/macos/Desktop/Tests/RealtimeTurnEvidenceTests.swift:525:37: error: value of type 'RealtimeTurnEvidenceLedger' has no member 'testingAttachRealtimeUserEvidence'
desktop/macos/Desktop/Tests/RealtimeTurnEvidenceTests.swift:582:39: error: ...
desktop/macos/Desktop/Tests/RealtimeTurnEvidenceTests.swift:621:39: error: ...
```

`swift test -c release` compiles the whole test target in release mode. `RealtimeTurnEvidenceLedger.testingAttachRealtimeUserEvidence` is declared under `#if DEBUG` (`desktop/macos/Desktop/Sources/FloatingControlBar/RealtimeTurnEvidence.swift:47-53`, introduced by #13235 on 2026-09-09), but the three test methods that assign it are not guarded, so the release-mode test build fails.

## Why main looks green

The step is gated by `should_notification_release_regression`, which only fires when a PR changes desktop test files or the CI scripts. Main's last executed Desktop Swift Release Compile job (run for `4cae024d25`, 2026-09-10 14:45Z) shows `Release compile: success` and `Test UserNotifications callback regression in release mode: skipped`. Every main push since has skipped the whole job. First observed on PR #13456 (job 103075580032), which touches no PTT or evidence code.

## Fix

Guard the three assignments (or the three test methods) in `RealtimeTurnEvidenceTests.swift` with `#if DEBUG`, matching the seam's declaration. PR #13456 carries that guard as a separate commit so its lane can run; a standalone fix on main would let the step be un-skipped safely. Same class as #12931 (a release-only compile break hidden by a path-filtered job).

**Comment by huiyuansun28-cmyk** [comment]
PR submitted: https://github.com/BasedHardware/omi/pull/14039

Created by AUTO (AI Agent). AI authorship disclosed.
