### PR TITLE
fix(python-sdk): require compatible websockets handshake API

### LINKED ISSUE #12953: Python SDK permits websockets versions that cannot connect to Deepgram
**Product impact**
Primary loop layer: Understand. The Python SDK can install an allowed dependency version but never produce a Deepgram transcript. No data-loss claim is made.

**Describe the bug**
Both `sdks/python/pyproject.toml` and `sdks/python/requirements.txt` allow `websockets>=10.0`, while `DeepgramTranscriber.run()` passes `additional_headers` to the top-level `websockets.connect()` alias. That alias uses the new asyncio implementation only from websockets 14.0 onward.

**To reproduce / evidence**
On main `7163538913e15dd86534b41dc695e2a5639c0774`, I exercised the actual SDK transcriber with Python 3.11.15 and websockets 13.1, redirecting its connection to loopback. Before a connection is opened, it prints:

```text
Deepgram error: BaseEventLoop.create_connection() got an unexpected keyword argument 'additional_headers'
```

The transcriber catches this exception and retries indefinitely. This does not require an Omi device or a real API key. The dependency/API boundary is documented in the [websockets migration guide](https://websockets.readthedocs.io/en/stable/howto/upgrade.html#arguments-of-connect).

**Expected behavior**
An installation satisfying the declared dependencies should support the handshake API the SDK uses.

**Environment**
Python SDK on macOS, Python 3.11.15. Smartphone, device version, browser and user ID: not applicable; no user account or physical hardware was used.

**Correction prepared locally**
I have a small patch raising both dependency floors to `websockets>=14.0`, updating the SDK guide and adding a handshake regression. All 8 SDK tests pass on 14.0 and 17.0.1; the new regression fails on 13.1. A separate real loopback test on 14.0 verified the Authorization header, 160 bytes of synthetic PCM and the returned transcript. Repository preflight/CI integration is being completed; live Deepgram and physical hardware have not been tested. This is separate from the reconnect-lifecycle defect in #12945.

Following the [contribution guide](https://github.com/BasedHardware/omi/blob/main/docs/doc/developer/Contribution.mdx), would @josancamon19 consider a **US$10 bounty paid through PayPal after acceptance and merge** for this correction? The work is AI-assisted. No reward or payment is assumed; payment details would be sent only through the documented private claim channel.

### PR DESCRIPTION
**Pull request by lucasmariano003-wq**
## What changed and why

The Python SDK allowed websockets 10–13 while its Deepgram client uses `additional_headers`, supported by the default asyncio client from 14.0. A valid installation with 13.1 failed before connecting and retried indefinitely. This raises the minimum to 14.0 in both manifests, documents it, and adds a minimum-version SDK test lane to the existing check manifest.

Fixes #12953. No runtime implementation or reconnect-policy changes. The API boundary follows the [websockets migration guide](https://websockets.readthedocs.io/en/stable/howto/upgrade.html).

## Product invariants affected

none

## How it was verified

- Python 3.11.15: all 8 SDK tests pass with websockets 14.0 and 17.0.1.
- Negative control: the new regression fails with 13.1 because `additional_headers` reaches the TCP function.
- Real loopback WebSocket smoke on 14.0 verified Authorization, 160 synthetic PCM bytes and the returned transcript. No real credentials, audio, Bluetooth hardware or provider API was used.
- Built wheel metadata requires `websockets>=14.0`, excluding 13.1.
- All 13 selected local manifest checks passed on these six paths, including the 47-test manifest contract suite. The initially skipped 90-day failure-class guard was then run with full Git history and passed.
- Pinned Black 26.5.1, shell syntax and `git diff --check` passed.
- The published six-file tree was fetched back and its SHA-256 hashes matched the locally verified files.

## Tests

`sdks/python/tests/test_deepgram_handshake.py` exercises the actual SDK and WebSocket library while replacing only the TCP boundary. It verifies the Authorization handshake and transcript callback. `bash sdks/python/test.sh` installs the dependency floor declared in requirements.txt, so lowering that floor also exercises the incompatible version.

## Failure class (fixes)

Failure-Class: none

## New guards

The `python-device-sdk-tests` manifest entry catches the reproduced dependency/API mismatch in #12953. This is a package-specific compatibility contract, so it belongs in the SDK runner; dispatch and change detection reuse the existing shared manifest.

This contribution was prepared and validated with an AI coding assistant. Physical hardware, live Deepgram and remote CI were not claimed as tested.

<a href="https://cubic.dev/pr/BasedHardware/omi/pull/12973?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Comment by lucasmariano003-wq** [comment]
Addressed the three cubic findings in 3743da2 and 2063528:

- Troubleshooting and its upgrade command now consistently require `websockets>=14.0`.
- The regression propagates the first unexpected retry exception directly and waits for either the worker failure or the transcript callback. The 13.1 negative control now reports its original `TypeError` in 0.06 seconds instead of an opaque timeout.
- The test queues 160 bytes of synthetic PCM, verifies the exact `send()` payload, and returns the transcript only after the send.

All 8 SDK tests pass with websockets 14.0 and 17.0.1; all 13 selected local preflight checks passed. The two published files were fetched back and their hashes match the tested copies. Runtime implementation and retry policy are unchanged.

@josancamon19, could the team approve the fork workflows for review and confirm whether the US$10 bounty proposed in #12953 is available for this fix? No reward or payment is assumed before acceptance.

**Comment by Git-on-my-level** [comment]
Verified this end to end. Summary for maintainers and @lucasmariano003-wq:

**Local verification (head 2063528):**
- `bash sdks/python/test.sh` with websockets pinned to the 14.0 floor: 8/8 tests pass.
- Latest websockets 17.0.1: 8/8 pass.
- Negative control at 13.1: the new regression fails immediately with the exact production error from #12953 (`create_connection() got an unexpected keyword argument 'additional_headers'`) instead of silently retrying — the fail-fast retry propagation works as described.

**Per-file:**
- `sdks/python/pyproject.toml`, `sdks/python/requirements.txt` — floor raised `websockets>=10.0` → `>=14.0` in both manifests, matching `DeepgramTranscriber.run()`'s `additional_headers=` handshake kwarg (accepted by the asyncio implementation from 14.0 per the migration guide). Correct minimal fix; no runtime implementation or retry-policy changes.
- `sdks/python/tests/test_deepgram_handshake.py` — drives the real transcriber with only the TCP boundary stubbed, and asserts the `Authorization: Token …` handshake header, the exact PCM payload sent, and the transcript callback. All monkeypatching (`getproxies`, `create_connection`, `sleep`) is test-scoped; no production behavior is altered.
- `sdks/python/test.sh` — network-free, strict-mode; `uv run --no-project` installs pytest 8.4.1 plus websockets pinned from `requirements.txt` via a single-source-of-truth regex. One minor note: that minimal environment works because the exercised `omi` modules are stdlib-only; future SDK tests importing `bleak`/`opuslib` would need this script extended. Non-blocking.
- `.github/checks-manifest.yaml` — new `python-device-sdk-tests` entry follows the existing schema (id/command/triggers/lanes/reason), triggers on `sdks/python/**` plus the manifest itself, `lanes: [local, ci]` like its siblings. GitHub shows no check runs for this PR yet (fork), so the lane has no CI evidence on GitHub itself; the local runs above stand in for now.
- `docs/doc/developer/sdk/python.mdx` — the 14.0 requirement is documented up front, the Troubleshooting section is now consistent with it (`websockets>=14.0` and a versioned upgrade command), and `test.sh` usage is documented.

The three earlier review findings (docs contradiction, swallowed retry exceptions, ineffective send guard) are all addressed in 3743da2/2063528 — the review timeline simply predates those commits.

Raising a published dependency floor and adding a shared CI lane are maintainer calls, so leaving those for sign-off before merge; the workflow-approval and bounty questions above are also for @josancamon19. Thank you for the exceptionally thorough verification write-up and the regression test — an exemplary first contribution.

— automated review on behalf of the Omi maintainers

---
*by AI on behalf of David — if you need David’s attention urgently, please @Git-on-my-level and escalate with `need human response`.*

**Review by kodjima33 — APPROVED** [review]
Bug fix, confidence 5/5: root cause stated (websockets 13.1 lacks additional_headers), fixes #12953, scoped diff (123 lines), regression test added and proven to fail pre-fix, verified not already fixed on main (requirements.txt still says websockets>=10.0).

**Comment by aryanorastar** [comment]
Keeping this open on `20635282c687`.

DIRTY 0-CI python websockets handshake pin + tests; kodjima APPROVE ≠ merge; rebase.

kodjima APPROVE is the size gate, not maintainer merge.

I am not approving or merging this SHA.

**Comment by aryanorastar** [comment]
Deepgram on main still passes `additional_headers` while `websockets` is pinned at `>=10.0`. This head raises the floor and adds `test_deepgram_handshake.py`. `20635282c687` conflicts and has no checks, so rebase it. This stays open and unapproved.

— Astar, on behalf of @aryanorastar

**Comment by lucasmariano003-wq** [comment]
Updated head: `644e7888a68a`. Rebased this PR onto current upstream main (`ae7858247209`). The conflict in `.github/checks-manifest.yaml` is resolved with all upstream checks preserved and the Python SDK check retained.

The current upstream SDK also introduced BLE tests and Deepgram `CloseStream` shutdown. I updated the test runner to provision the existing pinned `bleak` dependency and adjusted the handshake regression to verify both the exact 160-byte synthetic PCM payload and the shutdown message. The change remains confined to the same six files; upstream runtime behavior is preserved.

Fresh validation on Python 3.11.16:
- `bash sdks/python/test.sh`: 47 tests passed with websockets 14.0.
- Full SDK suite with websockets 17.0.1: 47 tests passed.
- Negative control with 13.1: the handshake regression fails immediately (0.06s) with the expected `additional_headers` TypeError.
- `make preflight` and `scripts/pr-preflight --pr-body-file ...`: all 13 selected checks passed, including 53 manifest contract tests.
- Built wheel metadata confirms `websockets>=14.0`; both dependency manifests and documentation agree.
- Black 26.5.1, shell syntax, and diff hygiene checks passed.

No live Deepgram service, physical Bluetooth device, or remote CI is claimed as tested. The previous workflow run ended with `action_required`, not a test failure.

@josancamon19 @aryanorastar, could a maintainer please approve the fork workflows for the updated head and give the dependency floor / shared CI entry a final review? Thank you.

**Comment by aryanorastar** [comment]
Keeping this open. Not approving `644e7888a68a`. origin/main `sdks/python/pyproject.toml` still allows `websockets>=10.0` while Deepgram connects with `additional_headers`. This SHA (moved off the older dirty head) raises the floor to `>=14` and adds `tests/test_deepgram_handshake.py`. Rollup is cubic-only. mergeable MERGEABLE/UNSTABLE.

— Astar, on behalf of @aryanorastar

**Review by kodjima33 — APPROVED** [review]
Bug fix, 5/5: root cause stated (websockets 13.1 lacks additional_headers needed by the Deepgram client), fixes #12953, scoped diff (123 lines), regression test proven to fail pre-fix, CI green (21/21), mergeStateStatus CLEAN, verified not already fixed on main.
