### PR TITLE
[codex] Guard transcribe cache NotFound test stub

### PR DESCRIPTION
**Pull request by tianmind-studio**
## Summary

- Keep `test_transcribe_conversation_cache.py` importable when earlier lightweight tests leave an empty `google.api_core.exceptions` stub in `sys.modules`.
- Prefer the real `google.api_core.exceptions.NotFound` when available, and only install a test-local fallback on import failure.
- Leave production transcribe/cache code unchanged.

## Root Cause

`test_firestore_read_ops_cache.py` stubs several Google modules, including `google.api_core.exceptions`, without adding `NotFound`. When pytest collects `test_transcribe_conversation_cache.py` later in the same process, `from google.api_core.exceptions import NotFound` fails even though the test passes in isolation.

Before this change:

- `python -m pytest backend\tests\unit\test_firestore_read_ops_cache.py backend\tests\unit\test_transcribe_conversation_cache.py --collect-only -q --tb=short` -> `ImportError: cannot import name 'NotFound' from 'google.api_core.exceptions'`

## Validation

- `python -m pytest backend\tests\unit\test_transcribe_conversation_cache.py -q --tb=short` -> 17 passed, 1 warning
- `python -m pytest backend\tests\unit\test_firestore_read_ops_cache.py backend\tests\unit\test_transcribe_conversation_cache.py --collect-only -q --tb=short` -> 68 tests collected
- `python -m pytest backend\tests\unit\test_transcribe_conversation_cache.py backend\tests\unit\test_firestore_read_ops_cache.py --collect-only -q --tb=short` -> 68 tests collected
- `python -m py_compile backend\tests\unit\test_transcribe_conversation_cache.py`
- `python -m black --line-length 120 --skip-string-normalization --check backend\tests\unit\test_transcribe_conversation_cache.py`
- `git diff --check`
- `scripts/pre-commit` with local Dart SDK + backend venv on PATH

### CODE REVIEW

**Review by kodjima33 — APPROVED** [review]
Test-only stabilization (transcribe cache NotFound stub), CI green
