### PR TITLE
[codex] Harden sync decode import stubs

### PR DESCRIPTION
**Pull request by tianmind-studio**
## Summary

- make the PCM and Opus sync decode tests repair stale import stubs before importing `routers.sync`
- add `utils.cloud_tasks` to the existing import-time stub lists so an earlier empty `utils` package stub does not hide that dependency
- ensure the other `routers.sync` import surfaces used during collection are present when prior tests leave partial module stubs in `sys.modules`
- keep the decode tests focused on local WAL decode behavior without relying on test collection order

## Root cause

`test_sync_pcm_decode.py` and `test_sync_opus_decode.py` pass in isolation, but after `test_action_item_date_validation.py` they can collect against stale package stubs left in `sys.modules`. In that order, `opuslib` may already exist without `Decoder`, and `utils` may have an empty package path that hides `utils.cloud_tasks`, causing `routers.sync` import to fail before decode assertions run.

A broader unit-test collection pass also showed the same pattern for additional `routers.sync` import-time dependencies such as `database.conversations`, `models.conversation`, STT helpers, speaker helpers, BYOK helpers, and subscription helpers. This PR makes the decode tests restore those expected stub attributes without overriding real module attributes.

## Validation

- before fix: `python -m pytest backend\tests\unit\test_action_item_date_validation.py backend\tests\unit\test_sync_pcm_decode.py --collect-only -q --tb=short --continue-on-collection-errors` -> `ImportError: cannot import name 'Decoder' from 'opuslib'`
- before fix: `python -m pytest backend\tests\unit\test_action_item_date_validation.py backend\tests\unit\test_sync_opus_decode.py --collect-only -q --tb=short --continue-on-collection-errors` -> `ImportError: cannot import name 'Decoder' from 'opuslib'`
- `python -m pytest backend\tests\unit\test_action_item_date_validation.py backend\tests\unit\test_sync_pcm_decode.py --collect-only -q --tb=short --continue-on-collection-errors` -> 49 collected
- `python -m pytest backend\tests\unit\test_action_item_date_validation.py backend\tests\unit\test_sync_opus_decode.py --collect-only -q --tb=short --continue-on-collection-errors` -> 47 collected
- `python -m pytest backend\tests\unit\test_sync_pcm_decode.py backend\tests\unit\test_sync_opus_decode.py -q --tb=short` -> 44 passed
- `python -m pytest backend\tests\unit\test_action_item_date_validation.py backend\tests\unit\test_sync_pcm_decode.py backend\tests\unit\test_sync_opus_decode.py -q --tb=short` -> 70 passed
- `python -m pytest backend\tests\unit --collect-only -q --tb=short --continue-on-collection-errors` -> no `backend\tests\unit\test_sync_*` collection errors; 3358 tests collected, 20 unrelated collection errors remain
- `black --line-length 120 --skip-string-normalization --check backend\tests\unit\test_sync_pcm_decode.py backend\tests\unit\test_sync_opus_decode.py`
- `python -m py_compile backend\tests\unit\test_sync_pcm_decode.py backend\tests\unit\test_sync_opus_decode.py`
- `git diff --check`
- `C:\Program Files\Git\bin\bash.exe scripts/pre-commit`

### CODE REVIEW

**Review by kodjima33 — APPROVED** [review]
Test-only stabilization (import isolation / stubs); zero product risk, CI not failing.
