### PR TITLE
fix(omi-hacker-news-app): guard non-dict payloads, validate item_id, and safe limit bounds (#14283)

### LINKED ISSUE #14283: fix(omi-hacker-news-app): guard non-dict payloads, validate item_id, and safe limit bounds
### Problem Description
In `plugins/omi-hacker-news-app/main.py`, several reliability and error-handling bugs can lead to unhandled 500 exceptions and malformed API requests:

1. **Crash on Null or Non-Dict Request Body:** `get_front_page`, `search_stories`, and `get_discussion` expect a `payload: dict[str, Any]` and call `payload.get(...)`. When client invocations send empty/null JSON bodies or non-dict payloads, `AttributeError: 'NoneType' object has no attribute 'get'` is raised.
2. **Missing `item_id` Type & Range Validation:** In `get_discussion`, `int(item_id)` is invoked without validating whether `item_id` is a boolean (in Python, `int(True) == 1`), empty string, or non-positive integer. Sending `0` or negative numbers generates malformed requests to `/items/{id}`.
3. **Boolean Handling in `_safe_limit`:** In Python, `isinstance(True, int)` is `True`. Passing `limit: True` results in `limit=1` instead of falling back to default `10`.
4. **Malformed URL When `objectID` is Missing:** When Algolia returns a hit with missing `objectID` / `story_id`, `_format_story` constructs invalid URLs ending with `item?id=None`.

### Proposed Solution
- Add `_safe_payload` helper ensuring any non-dict input safely defaults to `{}` without raising `AttributeError`.
- Harden `_safe_limit` to reject boolean values (`True`/`False`) and clamp safely between `1` and `MAX_LIMIT`.
- Add strict validation for `item_id`: reject booleans, empty strings, and non-positive integers with clean error messages (`"item_id must be a positive integer"`).
- Omit or format fallback URLs cleanly when `objectID` is absent.
- Extend `test_main.py` with unit tests for safe limits, non-dict payloads, missing object IDs, and item ID boundary validation.

Proposed bounty: $50

### PR DESCRIPTION
**Pull request by PINYOPATTANAWASANPORN**
### Summary of Changes
- Introduced `_safe_payload()` to prevent unhandled `AttributeError: 'NoneType' object has no attribute 'get'` when requests arrive with `null` or non-dict payloads.
- Hardened `_safe_limit()` to disallow boolean inputs and safely clamp integer limits between `1` and `MAX_LIMIT`.
- Hardened `get_discussion` to validate `item_id`: rejects `None`, booleans, empty strings, and non-positive numbers with clear validation error messages before calling downstream API.
- Fixed `_format_story` URL construction to prevent rendering `item?id=None` when `objectID` is omitted.
- Expanded hermetic regression tests in `test_main.py` covering all new guard paths.

Fixes #14283

Failure-Class: none

<a href="https://cubic.dev/pr/BasedHardware/omi/pull/14284?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Comment by Git-on-my-level** [comment]
Thanks @PINYOPATTANAWASANPORN - this is a tidy hardening pass that addresses all four failure modes from #14283, with hermetic regression tests to match. Reviewed both changed files:

**plugins/omi-hacker-news-app/main.py**
- `_safe_payload()` plus `payload: Any = None` on all three tool endpoints cleanly removes the `AttributeError: 'NoneType' object has no attribute 'get'` 500s on null/non-dict bodies; each handler now coerces before first use.
- `_safe_limit()` rejecting bools is a real fix - `isinstance(True, int)` in Python previously mapped `limit: true` to 1 instead of the default 10.
- `get_discussion` item_id validation is well layered: bools/None/empty short-circuit, `int()` failures for values like `"not-a-number"` still land in the existing `(ValueError, TypeError)` handler, and the new `<= 0` check stops malformed `/items/0` or negative requests before they reach Algolia. Micro-nit, non-blocking: a bool `item_id` returns "Missing required field: item_id" rather than a type-specific message - fine as-is.
- `_format_story` building `hn_url` once and gating the `HN:` line on `object_id` removes the `item?id=None` output and also fixes the subtle old bug where the fallback URL could still hardcode a missing id.

**plugins/omi-hacker-news-app/test_main.py**
- Good coverage of the new paths: `_safe_limit` boundary clamps (1 and MAX_LIMIT), bool rejection, unparseable inputs; missing-`objectID` formatting; a subTest-driven invalid-item_id matrix; and direct non-dict payload calls through all three handlers. The harness stays fully hermetic (stubbed httpx/fastapi/pydantic, no network).

Also confirmed the linked issue #14283 describes exactly these four defects, the tool manifest schema (`item_id` typed as integer, `required: ["item_id"]`) stays consistent with the new validation, and all 10 tests in `test_main.py` pass against this head. Checks are green (Hygiene, Backend Hermetic Merge Gate). Nothing blocking found - leaving merge sign-off with the human maintainers.

Feedback generated by automated maintainer tooling on behalf of the Omi maintainers.

---
*by AI on behalf of David — if you need David’s attention urgently, please @Git-on-my-level and escalate with `need human response`.*

**Review by Git-on-my-level — APPROVED** [review]
Obvious bugfix with tests; CI green on this head. Approving for admin squash.
